
---
title: "GrpPrjt_1"
author: "Joseph Gyamfi"
date: "June 15, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## R Code (Markdown) for Market Basket Analysis 
## by Group D (Amitabh Kumar, Jamie (Yeon Ju) Heo, Joseph Gyamfi, Rob Ness)

# Introduction
```{r}
##

```

# Dataset
```{r}
## We will use a dataset of Online Retail from http://archive.ics.uci.edu/ml/datasets/online+retail: Number of Rows:541,909, Number of Attributes: 8.
  # 1) InvoiceNo: Invoice number. Nominal, a 6-digit integral number uniquely assigned      to each transaction. If this code starts with letter 'c', it indicates a                cancellation. 
  # 2) StockCode: Product (item) code. Nominal, a 5-digit integral number uniquely          assigned to each distinct product.
  # 3) Description: Product (item) name. Nominal.
  # 4) Quantity: The quantities of each product (item) per transaction. Numeric.
  # 5) InvoiceDate: Invoice Date and time. Numeric, the day and time when each              transaction was generated. Example from dataset: 12/1/2010 8:26
  # 6) UnitPrice: Unit price. Numeric, Product price per unit in sterling.
  # 7) CustomerID: Customer number. Nominal, a 5-digit integral number uniquely assigned     to each customer.
  # 8) Country: Country name. Nominal, the name of the country where each customer          resides.
```

# Ethical ML Framework
```{r}
##


```

# Loading Libraries 
```{r}
#install and load package arules
#install.packages("arules")
library(arules)

#install and load arulesViz
#install.packages("arulesViz")
library(arulesViz)

#install and load readxml
#install.packages("readxml")
library(readxl)

#install and load knitr
#install.packages("knitr")
library(knitr)

#load ggplot2 as it comes in tidyverse
library(ggplot2)

#install and load plyr
#install.packages("plyr")
library(plyr)

#install and load dplyr
#install.packages("dplyr")
library(dplyr)
```

# Data Preparation
```{r}
#read excel into R dataframe
retail <- read_excel(file.choose())
```

```{r}
#complete.cases(data) returns a logical vector indicating which rows have no missing values. Then use the vector to get only rows that are complete using retail[,].
retail <- retail[complete.cases(retail), ]
summary (retail)
```

```{r}
#Use mutate function from dplyr package to edit or add new columns to dataframe. 
#Here Description column is being converted to factor column. as.factor converts column to factor column. %>% is an operator used to pipe values to another function or expression
retail %>% mutate(Description = as.factor(Description))
```

```{r}
#Similarly for Country column
retail %>% mutate(Country = as.factor(Country))
```

```{r}
#Converts character data to date. Store InvoiceDate as date in new variable
retail$Date <- as.Date(retail$InvoiceDate)
```

```{r}
#Extract time from InvoiceDate and store in another variable
TransTime<- format(retail$InvoiceDate,"%H:%M:%S")
```

```{r}
#Convert and edit InvoiceNo into numeric
InvoiceNo <- as.numeric(as.character(retail$InvoiceNo))     
```

```{r}
#Bind new columns TransTime and InvoiceNo into dataframe retail
cbind(retail,TransTime)
cbind(retail,InvoiceNo)
```

```{r}
#get a glimpse of your data
glimpse(retail)
```

```{r}
# Convert dataframe into transaction data before applying Association Rule Minding.
#Before applying Association Rule mining, we need to convert dataframe into transaction data so that all items that are bought together in one invoice are in one row. 
#You can see in glimpse output that each transaction is in atomic form, that is all products belonging to one invoice are atomic as in relational databases. This format is also called as the singles format.

#We need to group data in the retail dataframe either by CustomerID, CustomerID and Date or using InvoiceNo and Date. We need this grouping and apply a function on it and store the output in another dataframe. This can be done by ddply.

#The following lines of code combine all products from one InvoiceNo and date, and combine all products from that InvoiceNo and date as one row, with each item, separated by a comma 
#Syntax is  ddply(dataframe, variables_to_be_used_to_split_data_frame, function_to_be_applied)

transactionData <- ddply(retail,c("InvoiceNo","Date"),
                         function(df1)paste(df1$Description,
                                            collapse = ","))

#The R function paste() concatenates vectors to character and separated results using collapse=[any optional charcater string ]. Here ',' is used

#Show Dataframe transactionData
transactionData
```

```{r}
#Next, as InvoiceNo and Date will not be of any use in the rule mining, we set them to NULL
#set column InvoiceNo of dataframe transactionData  
transactionData$InvoiceNo <- NULL
#set column Date of dataframe transactionData
transactionData$Date <- NULL

#Show Dataframe transactionData
transactionData
```

```{r}
#Rename column to items
colnames(transactionData) <- c("items")

#Show Dataframe transactionData
transactionData
```

```{r}
#This format for transaction data is called the basket format. Next, we store this transaction data into a .csv (Comma Separated Values) file. 
#We use write.csv()
#quote: If TRUE it will surround character or factor column with double quotes. If FALSE nothing will be quoted
#row.names: either a logical value indicating whether the row names of x are to be written along with x, or a character vector of row names to be written.

write.csv(transactionData,file = "C:/Users/Administrator/Desktop/transactionData.csv", quote = FALSE, row.names = FALSE)
```

```{r}
#Next, load the transaction data into an object of the transaction class. This is done by using the R function read.transactions of the arules package.
#The following line of code will take the transaction data file market_basket_transactions.csv which is in basket format and convert it into an 
#object of the transaction class.
tr <- read.transactions('C:/Users/Administrator/Desktop/transactionData.csv', format = 'basket', sep=',')



#sep tells how items are separated. In this case we have separated items by comma

#Use summary to see item-set distribution


```

```{r}
#Generate an itemFrequencyPlot to create an item Frequency Bar Plot to view the distribution of objects based on 
#itemMatrix (e.g., >transactions or items in >itemsets and >rules) which is our case.

# Create an item frequency plot for the top 20 items
if (!require("RColorBrewer")) {
  # install color package of R
  install.packages("RColorBrewer")
  #include library RColorBrewer
  library(RColorBrewer)
}
itemFrequencyPlot(tr,topN=20,type="absolute",col=brewer.pal(8,'Pastel2'), main="Absolute Item Frequency Plot")
itemFrequencyPlot(tr,topN=20,type="relative",col=brewer.pal(8,'Pastel2'),main="Relative Item Frequency Plot")
```

# Mine Association Rules
```{r}
#This plot shows that 'WHITE HANGING HEART T-LIGHT HOLDER' and 'REGENCY CAKESTAND 3 TIER' have the most sales. 
#So to increase the sale of 'SET OF 3 CAKE TINS PANTRY DESIGN' the retailer can put it near 'REGENCY CAKESTAND 3 TIER'. 

#Generating Rules!
#Next step is to mine the rules using the APRIORI algorithm. The function apriori() is from package arules.
# Min Support as 0.001, confidence as 0.8.
association.rules <- apriori(tr, parameter = list(supp=0.001, conf=0.8,maxlen=10))

summary(association.rules)

inspect(association.rules[1:10])


```

```{r}
#For shorter length rules, reduce maxlen value
shorter.association.rules <- apriori(tr, parameter = list(supp=0.001, conf=0.8,maxlen=3))
```
```{r}
#Removing redundant rules
#We can remove rules that are subsets of larger rules as follows:

subset.rules <- which(colSums(is.subset(association.rules, association.rules)) > 1) # get subset rules in vector
```

```{r}
#which() returns the position of elements in the vector for which value is TRUE.
#colSums() forms a row and column sums for dataframes and numeric arrays.
#is.subset() Determines if elements of one vector contain all the elements of other

length(subset.rules)  

subset.association.rules. <- association.rules[-subset.rules] # remove subset rules.
```
```{r}
#Finding Rules related to given items
#Sometimes, you want to work on a specific product. If you want to find out what causes influence on the purchase of item X, you can 
#use appearance option in the apriori command. appearance gives us options to set LHS (IF part) and RHS (THEN part) of the rule.
#For example, to find what customers buy before buying 'METAL' run the following line of code:

metal.association.rules <- apriori(tr, parameter = list(supp=0.001, conf=0.8),appearance = list(default="lhs",rhs="METAL"))
```
```{r}
# Here lhs=METAL because you want to find out the probability of that in how many customers buy METAL along with other items
inspect(head(metal.association.rules))
```

```{r}
#Similarly, to find the answer to the question Customers who bought METAL also bought.... you will keep METAL on lhs:
metal.association.rules <- apriori(tr, parameter = list(supp=0.001, conf=0.8),appearance = list(lhs="METAL",default="rhs"))
```

```{r}
# Here lhs=METAL because you want to find out the probability of that in how many customers buy METAL along with other items
inspect(head(metal.association.rules))
```

#Visualizing Association Rules
```{r}
# (A) Scatter-Plot
#A straight-forward visualization of association rules is to use a scatter plot using plot() of the arulesViz package. 
#It uses Support and Confidence on the axes. In addition, a third measure Lift is used by default to color (grey levels) of the points.
# Filter rules with confidence greater than 0.4 or 40%
subRules<-association.rules[quality(association.rules)$confidence>0.4]
#Plot SubRules
plot(subRules)
```

```{r}
#The above plot shows that rules with high lift have low support. 
#You can use the following options for the plot: plot(rulesObject, measure, shading, method)
plot(subRules,method="two-key plot")
#The two-key plot uses support and confidence on x and y-axis respectively. It uses order for coloring. The order is the number of items in the rule.
```

```{r}
#(B) Interactive Scatter-Plot
#An amazing interactive plot can be used to present your rules that use arulesViz and plotly. 
#You can hover over each rule and view all quality measures (support, confidence and lift).
#Example
plotly_arules(subRules)
```

```{r}
# (C) Graph-Based Visualizations
#Graph-based techniques visualize association rules using vertices and edges where vertices are labeled with item names, and item sets or 
#rules are represented as a second set of vertices. Items are connected with item-sets/rules using directed arrows. Arrows pointing from 
#items to rule vertices indicate LHS items and an arrow from a rule to an item indicates the RHS. The size and color of vertices often 
#represent interest measures. 
#Graph plots are a great way to visualize rules but tend to become congested as the number of rules increases. So it is better to visualize 
#less number of rules with graph-based visualizations.

#Let's select 10 rules from subRules having the highest confidence.
top10subRules <- head(subRules, n = 10, by = "confidence")

#Now, plot an interactive graph. Note: You can make all your plots interactive using engine=htmlwidget parameter in plot
plot(top10subRules, method = "graph",  engine = "htmlwidget")

#From arulesViz graphs for sets of association rules can be exported in the GraphML format or as a Graphviz dot-file to be explored in tools like Gephi. For example, the 1000 rules with the highest lift are exported by:
saveAsGraph(head(subRules, n = 1000, by = "lift"), file = "rules.graphml")

```

```{r}
# (D) Individual Rule Representation
# This representation is also called as Parallel Coordinates Plot. It is useful to visualize which products 
#along with which items cause what kind of sales.

#As we know, the RHS is the Consequent or the item we propose the customer will buy; the positions are in the LHS where 2 is the most 
#recent addition to our basket and 1 is the item we previously had.
# Filter top 20 rules with highest lift
subRules2<-head(subRules, n=20, by="lift")
plot(subRules2, method="paracoord")

#Looking at the topmost arrow, the plot shows that when I have 'CHILDS GARDEN SPADE PINK' and 'CHILDS GARDEN RAKE PINK' in my shopping cart, I am likely to buy 'CHILDS GARDEN RAKE BLUE' along with these as well.
```








